#sort.behavior=list
#basic.msg.empty_list=No results matched your criteria.
basic.show.header=true
basic.empty.showtable=true
#page: paging then sorting,  list: sorting then paging
sort.amount=list
#Used when basic.empty.showtable=false
basic.msg.empty_list=Nothing found to display
#Used when basic.empty.showtable=true
basic.msg.empty_list_row=<tr><td colspan\="{0}" class\="noMatchData">\u7121\u7B26\u5408\u689D\u4EF6\u4E4B\u8CC7\u6599</td></tr></tr>
#top, bottom, both
paging.banner.placement=top
#<span class\="pagelinks">{0}</span>
paging.banner.onepage=
#page link count
paging.banner.group_size=10
#* {0}\: numbered pages list
#* {1}\: link to the first page
#* {2}\: link to the previous page
#* {3}\: link to the next page
#* {4}\: link to the last page
#* {5}\: current page
#* {6}\: total number of pages
#<span class\="pagelinks">[<a href\="{1}"><<</a>|<a href\="{2}"><</a>]{0}[<a href\="{3}">></a>|<a href\="{4}">>></a>]</span>
paging.banner.full=<span class\="pagelinks">[ <a href\="{1}" title\="\u7B2C\u4E00\u9801" onclick\="pagingSubmit( this );return false;"><<</a> | <a href\="{2}" title\="\u4E0A\u4E00\u9801" onclick\="pagingSubmit( this );return false;"><</a> ] {0} [ <a href\="{3}" title\="\u4E0B\u4E00\u9801" onclick\="pagingSubmit( this );return false;">></a> | <a href\="{4}" title\="\u6700\u5F8C\u4E00\u9801" onclick\="pagingSubmit( this );return false;">>></a> ] <span class="totalPages">\u5171 {6} \u9801</span></span>
#* {0}\: numbered pages list
#* {1}\: link to the first page
#* {2}\: link to the previous page
#* {3}\: link to the next page
#* {4}\: link to the last page
#* {5}\: current page
#* {6}\: total number of pages
#<span class\="pagelinks">[<< | <] {0}[<a href\="{3}">></a> | <a href\="{4}">>></a>]</span>
paging.banner.first=<span class\="pagelinks">[ << | < ] {0} [ <a href\="{3}" title\="\u4E0B\u4E00\u9801" onclick\="pagingSubmit( this );return false;">></a> | <a href\="{4}" title\="\u6700\u5F8C\u4E00\u9801" onclick\="pagingSubmit( this );return false;">>></a> ] <span class="totalPages">\u5171 {6} \u9801</span></span>
#* {0}\: numbered pages list
#* {1}\: link to the first page
#* {2}\: link to the previous page
#* {3}\: link to the next page
#* {4}\: link to the last page
#* {5}\: current page
#* {6}\: total number of pages
#<span class\="pagelinks">[<a href\="{1}"><<</a>/<a href\="{2}"><</a>]{0} [>/>>]</span>
paging.banner.last=<span class\="pagelinks">[ <a href\="{1}" title\="\u7B2C\u4E00\u9801" onclick\="pagingSubmit( this );return false;"><<</a> | <a href\="{2}" title\="\u4E0A\u4E00\u9801" onclick\="pagingSubmit( this );return false;"><</a> ] {0} [ > | >> ] <span class="totalPages">\u5171 {6} \u9801</span></span>
#Selected page. {0} is replaced with the page number, {1}
#with the page url.
paging.banner.page.selected=<strong>{0}</strong>
#Selected page. {0} is replaced with the page number, {1}
#with the page url.
#<a href\="{1}" title\="Go to page {0}">{0}</a>
paging.banner.page.link=<a href\="{1}" title\="\u7B2C {0} \u9801" onclick\="pagingSubmit( this );return false;">{0}</a>
paging.banner.page.separator=&nbsp;
paging.banner.item_name=item
paging.banner.items_name=items
#<span class\="pagebanner">No {0} found.</span>
paging.banner.no_items_found=
#* {0}\: total number of objects in the list
#* {1}\: name of the items (plural)
#* {2}\: start index of the objects being shown
#* {3}\: end index of the objects being shown
#* {4}\: current page
#* {5}\: total number of pages
#<span class\="pagebanner">{0} {1} found,displaying {2} to {3}.</span>
paging.banner.some_items_found=
#<span class\="pagebanner">One {0} found.</span>
paging.banner.one_item_found=
#<span class\="pagebanner">{0} {1} found,displaying all {2}.</span>
paging.banner.all_items_found=

#csv excel xml pdf rtf
export.types=excel pdf
export.excel=true
export.excel.class=org.displaytag.export.excel.DefaultHssfExportView
export.excel.label=<span class="export">Excel</span>
export.excel.include_header=true
#export.excel.filename=
export.csv=true
export.xml=true
export.pdf=true
export.pdf.class=org.displaytag.export.DefaultPdfExportView
export.pdf.label=<span class="export">Excel</span>
export.pdf.include_header=true
#export.pdf.filename=
export.rtf=true
export.rtf.class=org.displaytag.export.DefaultRtfExportView
export.banner=<div class="exportlinks">Export options: {0}</div>
export.banner.sepchar=|
#page: current page,  list: all data in the list
export.amount=list


# if set, file is downloaded instead of opened in the browser window
#export.[mymedia].filename=
css.tr.even=evenRow
css.tr.odd=oddRow
css.th.sorted=sorted
css.th.ascending=ascending
css.th.descending=descending
css.th.sortable=sortable
css.table=listTable