# To change this template, choose Tools | Templates
# and open the template in the editor.
# 
# Created On : 2015/8/11, \u4e0b\u5348 05:57:57, By \u8a31\u6b3d\u7a0b(Shiu Vincent)
# 
# ==============================================================================================
# $Id$
# ==============================================================================================
com.edstw.lang.IntegerString=com.edstw.struts2.converter.IntegerStringConverter
com.edstw.lang.DoubleString=com.edstw.struts2.converter.DoubleStringConverter
com.edstw.lang.LongString=com.edstw.struts2.converter.LongStringConverter
com.edstw.lang.DateString=com.edstw.struts2.converter.DateStringConverter
