# ==============================================================================================
# $Id: base_build.properties,v 1.2 2018/05/25 03:04:58 linsteph2\cvsuser Exp $
# ==============================================================================================

#The configuration file name of the application, the file should be kept inside src.conf.dir.
app.conf.file=app-config.xml
portal.app.conf.file=app-config-portal.xml
estate.app.conf.file=app-config-estate.xml

app.conf.encoding=utf-8
#The project specific configuration file name, must be set at project properties file.
proj.conf.file=proj-config.xml

src.dir=src

src.java.dir=${src.dir}/java

src.resource.dir=${src.dir}/resource

src.conf.dir=${src.dir}/conf

src.jasper.dir=${src.dir}/java/proj/nccc/logsearch/report

#\u5728build project\u6642\u662f\u5426\u8981compile jasper(jrxml)
precompile.jasper=false

src.test.dir=${src.dir}/test

src.generated.dir=${src.dir}/generated

#If XML Schema is used to generate java code, the following properties must be set
#Specify schema files' directory
src.schema.dir=${src.dir}/schema

#Specify the package name of generated java source
src.schema.generated.package=proj.nccc.${proj.name}.xsd

#Specify the jar name of compiled java classes, and the jar file will be copied to build.lib.dir after finish.
src.schema.generated.jar=${proj.name}_xsd.jar

lib.dir=lib

lib.compile.dir=${lib.dir}/compile

lib.test.dir=${lib.dir}/test

#Libraries used at runtime, must be set at project properties file.
lib.runtime.dir=
#Output directory when build the project, must be set at project properties file.
build.dir=
#Output directory of classes when build the project, must be set at project properties file.
build.classes.dir=
#Output directory of configuation files when build the project, must be set at project properties file.
build.conf.dir=
#Output directory of resources when build the project, must be set at project properties file.
build.resource.dir=
#Output directory of libraries when build the project, must be set at project properties file.
build.lib.dir=

#The file to exclude when copy files from java source to build.classes
copy.java.excludes=**/*.java, **/.*

copy.resource.includes=**/*.*

copy.conf.includes=**/*.*

copy.conf.excludes=*_web.xml, application.xml, ${server.web.conf}, ${server.app.conf}

copy.lib.includes=*.jar

compile.encoding=utf-8

#Argument 'source' for javac
compile.source=1.8

#Argument 'target' for javac
compile.target=1.8

doc.dir=doc

doc.todo.dir=${doc.dir}/todo

doc.javadoc.dir=${doc.dir}/javadoc

doc.fixme.dir=${doc.dir}/fixme

doc.test.report.dir=${doc.dir}/test_report

test.testcases.excludes=**/Test*Setup*.class,**/*Test$*
