#Created by JInto - www.guh-software.de
#Mon Mar 16 11:31:50 CST 2009
proj.cvs.cvsroot=/nccc_root
proj.cvs.module=LogSearch
proj.cvs.server=w2pz046w03
proj.name=atslog
web.context.root=atslog
proj.title=ATS LOG \u67E5\u8A62\u7CFB\u7D71
estate.proj.name=atslog_estate
estate.web.context.root=atslog_estate
estate.proj.title=ATS LOG \u67E5\u8A62\u7CFB\u7D71(ESTM)

log.log4j.conf=log4j2.xml

local.log.file=/u01/APPSVRLOG/LOG/${proj.name}/
production.log.file=/u01/APPSVRLOG/LOG/${proj.name}/
testing.log.file=/u01/APPSVRLOG/LOG/${proj.name}/