# ==============================================================================================
# $Id: library.properties,v 1.1 2014/01/02 02:56:21 asiapacific\hungmike Exp $
# ==============================================================================================

available.library.names=edstw,nccctw,edstw_testing,persist_comp

# ------------------------------------------------
# edstw Project property section
# ------------------------------------------------

edstw.cvs.server=w2sz12tk03

edstw.cvs.cvsroot=/eds_framework_root

edstw.cvs.module=edstw

edstw.build.file=build.xml

edstw.build.target=obfuscate

edstw.build.type=project

edstw.project.dir=D:\\projects\\eds\\edstw

edstw.library.path=dist

edstw.library.jar=edstw.jar

edstw.library.dest.dir=${web.lib.dir}

# ------------------------------------------------
# nccctw Project property section
# ------------------------------------------------

nccctw.cvs.server=w2sz12tk03

nccctw.cvs.cvsroot=/nccc_root

nccctw.cvs.module=nccctw

nccctw.build.file=build.xml

nccctw.build.target=obfuscate

nccctw.build.type=project

nccctw.project.dir=D:\\projects\\nccc\\nccctw

nccctw.library.path=dist

nccctw.library.jar=nccctw.jar

nccctw.library.dest.dir=${web.lib.dir}

# ------------------------------------------------
# EDS Testing Project property section
# ------------------------------------------------

edstw_testing.cvs.server=w2sz12tk03

edstw_testing.cvs.cvsroot=/eds_framework_root

edstw_testing.cvs.module=edstw_testing

edstw_testing.build.file=build.xml

edstw_testing.build.target=obfuscate

edstw_testing.build.type=project

edstw_testing.project.dir=D:\\projects\\eds\\edstw_testing

edstw_testing.library.path=dist

edstw_testing.library.jar=edstw_testing.jar

edstw_testing.library.dest.dir=${lib.test.dir}

# ------------------------------------------------
# Persist Component Library property section
# ------------------------------------------------
persist_comp.cvs.server=w2sz12tk03

persist_comp.cvs.cvsroot=/nccc_root

persist_comp.cvs.module=persist_comp

persist_comp.build.file=build.xml

persist_comp.build.target=obfuscate

persist_comp.build.type=project

persist_comp.project.dir=D:\\projects\\nccc\\persist_comp

persist_comp.library.path=dist

persist_comp.library.jar=persist_comp.jar

persist_comp.library.dest.dir=${web.lib.dir}
