# ==============================================================================================
# $Id: nccc_build.properties,v 1.1 2017/01/19 10:08:28 linsteph2\cvsuser Exp $
# ==============================================================================================

web.xml.local=local_web.xml

web.xml.nccc=nccc_web.xml

estate.web.xml.nccc=estate_web.xml

estate.web.xml.local=estate_web.xml

# ------------------------------------------------
# FTP Server property section
# ------------------------------------------------

ftp.dir=/prod_data/${proj.name}/ear

ftp.testing.dir=${ftp.dir}/testing

ftp.production.dir=${ftp.dir}/production

atslog.deploy=Y
estate.deploy=Y