# ==============================================================================================
# $Id: web_base_build.properties,v 1.1 2017/01/19 10:08:28 linsteph2\cvsuser Exp $
# ==============================================================================================

src.javascript.dir=src/javascript

web.directory=web-module

web.lib.dir=${web.directory}/WEB-INF/lib

web.classes.dir=${web.directory}/WEB-INF/classes

web.conf.dir=${web.directory}/WEB-INF/conf

javascript.dir=scripts

compress.javascript=false

javascript.compress.includes=**/*.js

javascript.compress.excludes=

javascript.compressor.jar=yuicompressor-2.3.5.jar

copy.javascript.includes=**/*.*

copy.javascript.excludes=

dist.dir=dist

war.excludes=**/.*

#following properties are used to override properties set in base_build.properties
lib.runtime.dir=${web.lib.dir}
#Output directory when build the project, must be set at project properties file.
build.dir=${web.directory}
#Output directory of classes when build the project, must be set at project properties file.
build.classes.dir=${web.classes.dir}
#Output directory of configuation files when build the project, must be set at project properties file.
build.conf.dir=${web.conf.dir}
#Output directory of resources when build the project, must be set at project properties file.
build.resource.dir=${web.classes.dir}
#Output directory of libraries when build the project, must be set at project properties file.
build.lib.dir=${web.lib.dir}

server.web.conf=

server.app.conf=ibm-web*.xml

server.app.metainf.includes=*.version
